In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import os
import pandas as pd

In [3]:
folder_path = "/content/drive/MyDrive/Colab Notebooks/datasets"
csv_file = "metadata.csv"

def load_data(folder_path, csv_path):
    csv_path = os.path.join(folder_path, csv_file)
    if not os.path.exists(csv_path):
      raise FileNotFoundError(f"{csv_file} not found. Make sure the file exists!")
    return pd.read_csv(csv_path)

meta_data = load_data(folder_path, csv_file)
meta_data.head()

,user,start_date,end_date,length_days,length_years,potential_samples,actual_samples,missing_samples_abs,missing_samples_pct,contract_start_date,...,p1,p2,p3,p4,p5,p6,province,municipality,zip_code,cnae
0,00000c5a448d9faa097b761cc98036d45a4e7d36032903...,2022-05-30T01:00:00Z,2022-06-05T00:00:00Z,6.0,0.016427,144,144,0,0.000000,2022-05-31,...,2.20,2.20,0.0,0.0,0.0,0.0,Gipuzkoa,NaN,NaN,9329.0
1,0001b3b2f18c01c62ed9b2a87de7b4e33e7836f786f790...,2017-05-31T01:00:00Z,2022-06-05T00:00:00Z,1831.0,5.013005,43944,43863,81,0.184326,2021-06-01,...,3.45,3.45,NaN,NaN,NaN,NaN,Bizkaia,NaN,NaN,9820.0
2,0003de2700e20a1681d69fe287441d9041407a7698d5c8...,2017-05-31T01:00:00Z,2019-11-14T00:00:00Z,897.0,2.455852,21528,21476,52,0.241546,2019-09-02,...,4.60,NaN,NaN,NaN,NaN,NaN,Gipuzkoa,Donostia/San Sebastian,20013.0,9820.0
3,0004150214d14a2b2e6f7075531e661cf465b27ec4d0d5...,2018-07-12T01:00:00Z,2022-06-05T00:00:00Z,1424.0,3.898700,34176,34169,7,0.020482,2021-06-01,...,9.20,9.20,NaN,NaN,NaN,NaN,Gipuzkoa,Irun,20304.0,4759.0
4,000721f0fc6ccf02ae24b67393979513171f2abc119af0...,2017-05-30T01:00:00Z,2022-06-04T00:00:00Z,1831.0,5.013005,43944,43815,129,0.293555,2021-06-01,...,4.40,4.40,NaN,NaN,NaN,NaN,Bizkaia,NaN,NaN,9820.0

Here i am structuring my grouping by zip_code!

In [4]:
meta_data = meta_data.dropna(subset = ["zip_code"])

In [5]:
meta_data.groupby("zip_code").size()

zip_code
1001.0     230
1002.0     178
1003.0     259
1004.0      43
1005.0      56
          ...
50011.0      1
50012.0      1
50019.0      1
50193.0      1
50617.0      1
Length: 434, dtype: int64

**Calculating the transformer capacity**

In [6]:
meta_data['max_power'] = meta_data[['p1','p2','p3','p4','p5','p6']].max(axis=1)
capacity = meta_data['max_power'].sum() * 0.8